import { Edit3, Search, Star, Users } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { PageHeader } from "../components/layout/PageHeader";
import { Modal } from "../components/ui/Modal";
import { api } from "../services/api";
import type { Cliente, Conversa, PaginaResponse } from "../types/api";

export function ClientesPage() {
  const [items, setItems] = useState<Cliente[]>([]); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<Cliente | null>(null); const [history, setHistory] = useState<Conversa[]>([]); const [reload, setReload] = useState(0); const [error, setError] = useState("");
  useEffect(() => { api.get<PaginaResponse<Cliente>>("/api/clientes?tamanho=100").then((x) => setItems(x.itens)).catch((e) => setError(e.message)); }, [reload]);
  async function open(cliente: Cliente) { setSelected(cliente); const data = await api.get<PaginaResponse<Conversa>>(`/api/clientes/${cliente.id}/conversas?tamanho=20`); setHistory(data.itens); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const d = new FormData(event.currentTarget); try { await api.put(`/api/clientes/${selected.id}`, { nome: d.get("nome"), email: d.get("email") || null, telefone: d.get("telefone") || null, vip: d.get("vip") === "on" }); setSelected(null); setReload((x) => x + 1); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao salvar."); } }
  const visible = items.filter((x) => `${x.nome} ${x.email} ${x.telefone}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="page"><PageHeader eyebrow="RELACIONAMENTO" title="Clientes" description="Cadastros e histórico de atendimento." /><div className="toolbar"><label className="search-field"><Search size={17} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar cliente" /></label></div>{error && <div className="form-error">{error}</div>}<section className="table-panel">{visible.length === 0 ? <div className="state-message"><Users /><strong>Nenhum cliente</strong></div> : <div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Contato</th><th>Cadastro</th><th /></tr></thead><tbody>{visible.map((x) => <tr key={x.id}><td><strong>{x.vip && <Star className="vip-star" size={13} fill="currentColor" />} {x.nome}</strong><small>#{x.id}</small></td><td>{x.email || "—"}<small>{x.telefone}</small></td><td>{new Date(x.dataCriacao).toLocaleDateString("pt-BR")}</td><td><button className="icon-button icon-button--border" onClick={() => void open(x)}><Edit3 size={16} /></button></td></tr>)}</tbody></table></div>}</section>{selected && <Modal title="Detalhes do cliente" onClose={() => setSelected(null)}><form className="entity-form" onSubmit={save}><div className="form-grid"><label>Nome<input name="nome" defaultValue={selected.nome} required /></label><label>E-mail<input name="email" type="email" defaultValue={selected.email ?? ""} /></label><label>Telefone<input name="telefone" defaultValue={selected.telefone ?? ""} /></label></div><label className="checkbox"><input name="vip" type="checkbox" defaultChecked={selected.vip} /> Cliente VIP</label><div className="modal-actions"><button type="button" className="button button--ghost" onClick={() => setSelected(null)}>Cancelar</button><button className="button button--primary">Salvar</button></div></form><div className="history-list"><h3>Histórico recente</h3>{history.map((x) => <div key={x.id}><strong>{x.setorNome}</strong><span>{x.status} · {new Date(x.dataAbertura).toLocaleDateString("pt-BR")}</span></div>)}</div></Modal>}</div>;
}
