import { CheckCircle2, Clock3, MessageSquareText, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "../auth/AuthContext";
import { PageHeader } from "../components/layout/PageHeader";
import { api } from "../services/api";
import type { Cliente, Conversa, PaginaResponse } from "../types/api";

export function DashboardPage() {
  const { usuario } = useAuth(); const [conversas, setConversas] = useState<Conversa[]>([]); const [clientTotal, setClientTotal] = useState(0); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.get<PaginaResponse<Conversa>>("/api/conversas?tamanho=100"), api.get<PaginaResponse<Cliente>>("/api/clientes?tamanho=1")]).then(([c, clients]) => { setConversas(c.itens); setClientTotal(clients.total); }).catch((e) => setError(e.message)); }, []);
  const today = new Date().toDateString(); const metrics = [{ label: "Em atendimento", value: conversas.filter((x) => x.status === "Active").length, detail: "Conversas ativas", icon: MessageSquareText, tone: "violet" }, { label: "Aguardando", value: conversas.filter((x) => x.status === "Waiting").length, detail: "Na fila agora", icon: Clock3, tone: "amber" }, { label: "Finalizadas hoje", value: conversas.filter((x) => x.status === "Closed" && x.dataEncerramento && new Date(x.dataEncerramento).toDateString() === today).length, detail: "Atendimentos", icon: CheckCircle2, tone: "green" }, { label: "Clientes", value: clientTotal, detail: "Total cadastrado", icon: Users, tone: "blue" }];
  const bySector = useMemo(() => Object.entries(conversas.filter((x) => x.status === "Waiting").reduce<Record<string, number>>((acc, x) => { const name = x.setorNome ?? "Sem setor"; acc[name] = (acc[name] ?? 0) + 1; return acc; }, {})), [conversas]);
  return <div className="page"><PageHeader eyebrow="PAINEL" title={`Olá, ${usuario?.nome.split(" ")[0]}!`} description="Acompanhe o movimento da sua operação em um só lugar." />{error && <div className="form-error">{error}</div>}<section className="metrics-grid">{metrics.map(({ label, value, detail, icon: Icon, tone }) => <article className="metric-card" key={label}><span className={`metric-card__icon metric-card__icon--${tone}`}><Icon size={21} /></span><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>)}</section><section className="content-grid"><article className="panel panel--large"><div className="panel__header"><div><h2>Conversas recentes</h2><p>Últimos atendimentos registrados</p></div></div><div className="dashboard-list">{conversas.slice(0, 6).map((x) => <div key={x.id}><span className="avatar">{(x.clienteNome ?? "C").slice(0, 2).toUpperCase()}</span><div><strong>{x.clienteNome}</strong><small>{x.setorNome}</small></div><span className="active-label">{x.status.replaceAll("_", " ")}</span></div>)}{conversas.length === 0 && <p>Nenhuma conversa registrada.</p>}</div></article><article className="panel"><div className="panel__header"><div><h2>Fila por setor</h2><p>Visão atual</p></div></div><div className="sector-queue">{bySector.map(([name, count]) => <div key={name}><span>{name}</span><strong>{count}</strong></div>)}{bySector.length === 0 && <p>Nenhuma conversa aguardando.</p>}</div></article></section></div>;
}
